import { hashPassword } from './password';
import type { SiteData } from './types';

export function createSeed(): SiteData {
  return {
    adminUser: 'admin',
    passwordHash: hashPassword('Navnikunj@123'),
    identity: {
      name: 'Navnikunj Foundation',
      tagline: 'Kindness · Hope · Better tomorrows',
      email: 'info@navnikunjfoundation.org',
      phone: '+91 96505 93996',
      phoneHref: '+919650593996',
      address: 'NAVNIKUNJ FOUNDATION\nLIG-12A/107, Suncity Anantam Kunj, Vrindaban,\nMathura- 281121, Uttar Pradesh, India',
      mapQuery: 'LIG-12A/107, Suncity Anantam Kunj, Vrindaban, Mathura 281121, Uttar Pradesh, India',
      facebook: '',
      instagram: '',
      youtube: '',
      linkedin: '',
    },
    hero: {
      eyebrow: 'Serving society through',
      title: 'Kindness that opens a better tomorrow',
      text: 'We stand with families who need a school place, a health visit, a meal, or a skill they can use. Every gift is tracked, and every program is built to last beyond a single day.',
      image: '',
    },
    stats: [
      { value: '1,200+', label: 'People supported' },
      { value: '18', label: 'Community programs' },
      { value: '6', label: 'Learning circles' },
      { value: '100%', label: 'Gifts recorded' },
    ],
    about: {
      eyebrow: 'About us',
      title: 'A foundation built on kindness, hope, and practical help',
      text: 'Navnikunj Foundation brings neighbours, teachers, and volunteers together so support reaches people in time. We focus on learning, health, family relief, work skills, and cleaner shared spaces. The work is local, the records are open to the team, and the aim is simple: help someone stand a little steadier.',
      quote: 'Kindness is the shortest path to a better tomorrow.',
      image: '',
    },
    cta: {
      title: 'Be part of the change',
      text: 'Your support keeps school kits, health camps, and family relief moving. Give once, or come back when you can.',
    },
    programs: [
      {
        id: 'pg_learn',
        slug: 'learning-support',
        title: 'Learning support',
        summary: 'School kits, fees, and after-school help so children can stay in class.',
        body: 'Learning support covers notebooks, uniforms, fee help, and a quiet hour after school with a volunteer. We work with families who would otherwise pull a child out of class when money runs short.',
        icon: 'book',
      },
      {
        id: 'pg_health',
        slug: 'community-health',
        title: 'Community health',
        summary: 'Health camps and basic care close to the neighbourhoods we serve.',
        body: 'Community health days bring a doctor, basic checks, and clear next steps. We tell families what was found and where to go if more care is needed.',
        icon: 'health',
      },
      {
        id: 'pg_relief',
        slug: 'family-relief',
        title: 'Family relief',
        summary: 'Food and daily essentials for households in a hard month.',
        body: 'When work stops or a bill lands at the wrong time, a ration kit and a follow-up visit keep a household going. Relief is short, personal, and recorded.',
        icon: 'heart',
      },
      {
        id: 'pg_skills',
        slug: 'skills-for-work',
        title: 'Skills for work',
        summary: 'Practical training that helps young people earn a steady income.',
        body: 'Short courses in communication, computer basics, and local trades are paired with a mentor. The goal is a first job or a small service the learner can offer.',
        icon: 'users',
      },
      {
        id: 'pg_green',
        slug: 'green-neighbourhoods',
        title: 'Green neighbourhoods',
        summary: 'Tree planting and clean-up drives that leave a street better than we found it.',
        body: 'Volunteers plant, water, and clear shared corners. Children join so the habit of looking after a place starts early.',
        icon: 'sprout',
      },
    ],
    posts: [
      {
        id: 'post_kits',
        slug: 'school-kit-drive',
        kind: 'news',
        title: 'School kit drive opens for the new term',
        excerpt: 'Notebooks, bags, and uniforms are being packed for children starting the term without supplies.',
        body: 'Volunteers are packing school kits this month. Each kit has notebooks, a bag, and the uniform pieces a school has asked for. Families can request a kit through the learning support program, and donors can cover a kit from the donate page.',
        image: '',
        date: '2026-08-20',
        location: 'Community centre',
        keywords: 'school kits, education, children',
        published: true,
      },
      {
        id: 'post_camp',
        slug: 'neighbourhood-health-camp',
        kind: 'event',
        title: 'Neighbourhood health camp',
        excerpt: 'A one-day camp for basic checks, with time set aside for parents and older residents.',
        body: 'The health camp runs from morning until late afternoon. Bring any earlier reports you have. Children, parents, and older residents are welcome. There is no fee.',
        image: '',
        date: '2026-09-12',
        location: 'Neighbourhood park gate',
        keywords: 'health camp, community health',
        published: true,
      },
      {
        id: 'post_sunday',
        slug: 'why-we-record-every-gift',
        kind: 'blog',
        title: 'Why we record every gift',
        excerpt: 'A short note on how donations are logged, so supporters can see that help reached a program.',
        body: 'Every donation is stored with a name, an amount, and a payment reference once Razorpay confirms it. The admin desk shows paid and unfinished checkouts separately. That record is how the team matches a gift to school kits, a health camp, or family relief.',
        image: '',
        date: '2026-07-28',
        location: '',
        keywords: 'donations, transparency',
        published: true,
      },
    ],
    gallery: [],
    messages: [],
    donations: [],
  };
}
